name: build-docker

# 触发条件
on:
  push:
    paths:
      - 'Dockerfile'

# 任务列表
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Debug event data
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Full event data: ${{ toJson(github.event) }}"
          echo "Added files: ${{ toJson(github.event.commit.added) }}"
          echo "Modified files: ${{ toJson(github.event.commit.modified) }}"

  # 镜像构建和推送任务
  build_and_push_image:
    # 运行环境
    runs-on: ubuntu-latest
    # 运行条件 => 当 Dockerfile 被创建或修改时触发
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
    # 镜像构建和推送任务的步骤列表
    steps:
      - name: Clean up unused files
        run: |
          sudo apt-get clean
          rm -rf ~/.cache/*
          df -h
      
      - name: Stop Docker service
        run: sudo systemctl stop docker

      - name: Move existing Docker data (if any)
        run: |
          if [ -d /var/lib/docker ]; then
            sudo mv /var/lib/docker/ /mnt/
          fi

      - name: Configure Docker to use /mnt/docker
        run: |
          echo '{
            "data-root": "/mnt/docker"
          }' | sudo tee /etc/docker/daemon.json

      - name: Start Docker service
        run: sudo systemctl start docker

      - name: Verify Docker storage directory
        run: docker info | grep "Docker Root Dir"
        
      # 1. 切换分支（默认主分支）
      - name: Check out code
        uses: actions/checkout@v2

      # 2. 提取 Dockerfile 的第一行注解作为镜像标签
      - name: Extract image tag from Dockerfile
        id: extract_tag
        run: |
          TAG=$(sed -n '1s/^# NAME: //p' Dockerfile)
          echo "Extracted tag: $TAG"
          echo "::set-output name=tag::$TAG"

      # 3. 登录阿里云容器镜像仓库
      - name: Log in to Alibaba Cloud Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # 4. 构建 Docker 镜像
      - name: Build Docker image
        run: DOCKER_BUILDKIT=1 docker build -t ${{ secrets.DOCKER_REPOSITORY }}/${{ steps.extract_tag.outputs.tag }} .

      # 5. 推送 Docker 镜像到阿里云容器镜像仓库
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_REPOSITORY }}/${{ steps.extract_tag.outputs.tag }}
